### ISSUE TITLE
CentOS 8 compatibility - php-mysql is called php-mysqlnd

### ISSUE THREAD

**Issue by tobiasehlert** [geerlingguy/ansible-role-php-mysql#7]
The packet php-mysql is renamed to php-mysqlnd in CentOS 8, so the playbook is failing, if not adjusting the application name with this var:

```
php_mysql_package:
  - php-mysqlnd
```

**Comment by otseng** [comment]
Thanks for the tip.

**Comment by geerlingguy** [comment]
Thanks; I'll try to get this role working on CentOS 8 soon!

**Comment by tobiasehlert** [comment]
@geerlingguy any update on the role to solve this? :-)

**Comment by williampiv** [comment]
Not sure if you want to solve it like this, but it seems like the easiest way to fix this would be to add a little logic to the RedHat.yml var file (vars/RedHat.yml) so that `__php_mysql_package: php-mysqlnd` becomes something like `__php_mysql_package: "{{ 'php-mysql' if ansible_distribution_major_version < '8' else 'php-mysqlnd' }}"`

I've tested this, and it looks like this works with CentOS 8 (and still works for CentOS 7). I am happy to put in a PR if that's more helpful.

**Comment by tobiasehlert** [comment]
@williampiv yeah, that is exactly what would be needed to get it resolved.
Make a PR for this, that would be awesome :)

**Comment by geerlingguy** [comment]
The strange thing is, the role is currently working in the centos8 CI test environment... https://github.com/geerlingguy/ansible-role-mysql/runs/1360686797

**Comment by eisenheimjelid** [comment]
Hi! I think the problem was not fixed: `["No package php-mysql available."], "msg": "Failed to install some of the specified packages"`

```
TASK [geerlingguy.php-mysql : Include OS-specific variables.] ******************
ok: [default] => {"ansible_facts": {"__php_mysql_package": "php-mysql"}, "ansible_included_var_files": ["/home/david/.ansible/roles/geerlingguy.php-mysql/vars/RedHat.yml"], "changed": false}

TASK [geerlingguy.php-mysql : Define php_mysql_package.] ***********************
ok: [default] => {"ansible_facts": {"php_mysql_package": "php-mysql"}, "changed": false}

TASK [geerlingguy.php-mysql : Install PHP MySQL dependencies (RedHat).] ********
fatal: [default]: FAILED! => {"changed": false, "failures": ["No package php-mysql available."], "msg": "Failed to install some of the specified packages", "rc": 1, "results": []}

RUNNING HANDLER [geerlingguy.php : restart webserver] **************************

PLAY RECAP *********************************************************************
default                    : ok=68   changed=5    unreachable=0    failed=1    skipped=38   rescued=0    ignored=0   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

I changed locally this file `/home/david/.ansible/roles/geerlingguy.php-mysql/vars/RedHat.yml` with this value:

```
__php_mysql_package: php-mysqlnd
```

After that I get this:

```
TASK [geerlingguy.php-mysql : Include OS-specific variables.] ******************
ok: [default] => {"ansible_facts": {"__php_mysql_package": "php-mysqlnd"}, "ansible_included_var_files": ["/home/david/.ansible/roles/geerlingguy.php-mysql/vars/RedHat.yml"], "changed": false}

TASK [geerlingguy.php-mysql : Define php_mysql_package.] ***********************
ok: [default] => {"ansible_facts": {"php_mysql_package": "php-mysqlnd"}, "changed": false}

TASK [geerlingguy.php-mysql : Install PHP MySQL dependencies (RedHat).] ********
changed: [default] => {"changed": true, "msg": "", "rc": 0, "results": ["Installed: php-mysqlnd-7.2.24-1.module_el8.2.0+313+b04d0a66.x86_64"]}

TASK [geerlingguy.php-mysql : Install PHP MySQL dependencies (Debian).] ********
skipping: [default] => {"changed": false, "skip_reason": "Conditional result was False"}
```

Finally, If you search `php-mysql` does not exist in Centos 8 https://pkgs.org/search/?q=php-mysql and only appears `php-mysqlnd` [https://centos.pkgs.org/8/centos-appstream-x86_64/php-mysqlnd-7.2.24-1.module_el8.2.0+313+b04d0a66.x86_64.rpm.html](https://centos.pkgs.org/8/centos-appstream-x86_64/php-mysqlnd-7.2.24-1.module_el8.2.0+313+b04d0a66.x86_64.rpm.html)
